### PR TITLE
Make the sort order of stations consistent

### LINKED ISSUE #12: Sort order of added stations is inconsistent
To reproduce add SEA_GND as a position.

Sometimes the stations will arrange like this:

image

But sometimes the SEA_GND and SEA_DEL will swap positions, with SEA_DEL getting listed first. I can't pinpoint why this happens, but I would expect the stations to always show in the same order.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #12

Draft pull request with the initial work for feedback. Summary of changes:

1. Add a new `RadioHelper.ts` file that includes a `radioCompare` method to compare two radios for sorting
2. Add a new `getCallsignParts` method that takes a callsign and splits it out into the station, position, and subposition
3. Add new `station`, `position`, and `subPosition` properties on a radio and set them when radios are added. These are used for sorting later
4.  Pass the connected station callsign through when adding radios

The sorting winds up being a bit of a pain to make things look right in the list. Here's the logic:

1. The connected station always goes to the front of the list
2. Remaining stations are sorted by station name, then by position, then by sub-position (if any)

In my playing around this seems to work well and makes for a sensible list.

I'm not a huge fan of passing through the connected station callsign to the addRadios method but I didn't see another way to do it without taking a dependency on `useSessionState` inside `useRadioState` which seemed bad. Let me know if you have other ideas here.

Untested (and likely not working) is sorting the connected callsign to the front of the list when connected via a relief position (e.g. SEA_1_GND). I think the way to resolve that is to actually store the cleaned connected station callsign in session state as well (so it doesn't keep getting computed), and use that instead of the regular station callsign in the sort method.

### CODE REVIEW

File: src/app/components/bootstrap.tsx [hunk 1]
```diff
@@ -27,7 +27,13 @@ const Bootsrap: React.FC = () => {
           console.error("Failed to add frequency", freq, station);
           return;
         }
-        useRadioState.getState().addRadio(freq, station);
+        useRadioState
+          .getState()
+          .addRadio(
+            freq,
+            station,
+            useSessionStore.getState().getStationCallsign()
```
Comment (neilenns) [inline src/app/components/bootstrap.tsx:35]: See my notes in the PR about this. I'm not a huge fan.

File: src/app/store/radioStore.ts [hunk 2]
```diff
@@ -73,12 +82,18 @@ const useRadioState = create<RadioState>((set) => ({
       );
       return;
     }
+
+    const [station, position, subPosition] = getCallsignParts(callsign);
```
Comment (neilenns) [inline src/app/store/radioStore.ts:86]: Calculate the sub-parts of the callsign so they can be stored with the radio when the radio is created.

File: src/app/store/radioStore.ts [hunk 3]
```diff
@@ -89,7 +104,7 @@ const useRadioState = create<RadioState>((set) => ({
           selected: false,
           transceiverCount: 0,
         },
-      ],
+      ].sort((a, b) => radioCompare(a, b, stationCallsign)),
```
Comment (neilenns) [inline src/app/store/radioStore.ts:107]: One line of magic to sort 😂

File: src/app/components/sidebar/add-frequency.tsx [hunk 4]
```diff
@@ -10,7 +10,9 @@ const AddFrequency: React.FC = () => {
     state.setRx,
   ]);
 
-  const isNetworkConnected = useSessionStore((state) => state.isNetworkConnected);
+  const isNetworkConnected = useSessionStore(
```
[the remark this answers is not in the document]
Comment (pierr3) [reply src/app/components/sidebar/add-frequency.tsx:13]: I'll re-prettier myself, so that'll get fixed :D

File: src/app/components/bootstrap.tsx (hunk 1 above)
Comment (pierr3) [reply src/app/components/bootstrap.tsx:35]: I'm not a fan but we have no choice as we cannot call the sessionStore outside of a functional component, I think this is honestly fine for now

**Comment by pierr3** [comment]
Great PR! The cleaned up callsign for relief position is already store in useSessionStore.stationCallsign. Since you're calling that already, you're good to go ! Can you please add in your documents that provide documentation an example with a standard ICAO callsign, like LFPG_N_TWR? This is simply to ensure that people will understand those are also explicitly supported

**Comment by neilenns** [comment]
Comments updated as requested
