### PR TITLE
Ensure CID always shows as a number

### LINKED ISSUE #127: CID incorrectly shows in scientific notation
[From Discord](https://discord.com/channels/699659614928502815/700872340103495681/1258910763754721391)

image

This was on Win11. Bruce looked in the config.json file and it is properly stored as a string value.

Pierre claims this is `1259390`.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #127

* Change the input field type to text instead of `number`
* Make the input field controlled
* Strip any non-digit characters from the input

I have no idea if this is actually the fix for the problem since I can't reproduce it. However, this was the only place in the code that attempted to treat the value as a number, so it's possible the browser happened to try and display it in scientific notation for some reason.

Tested on Windows that I can still type digits in, use the backspace key, and paste in a CID without issue. Any non-digit characters simply don't appear.

### CODE REVIEW

File: src/renderer/src/components/settings-modal/settings-modal.tsx [hunk 1]
```diff
@@ -207,12 +206,16 @@ const SettingsModal: React.FC<SettingsModalProps> = ({ closeModal }) => {
...
                     className="form-control mt-1"
                     id="cidInput"
                     placeholder="99999"
-                    defaultValue={cid}
-                    onChange={(e) => debouncedCid(e.target.value)}
+                    value={cid}
+                    onChange={(e) => {
+                      // Issue #127: Strip non-digit characters instead of using type="number".
+                      const cleanCid = e.target.value.replace(/\D/g, ''); // Remove non-digit characters
+                      setCid(cleanCid);
```
Comment (pierr3) [inline src/renderer/src/components/settings-modal/settings-modal.tsx:216]: You're effectively voiding the use of the debounce here, you should put all of this in the debounce function and have it execute only when the user is done entering the CID, there is no need for live update

Comment (neilenns) [reply src/renderer/src/components/settings-modal/settings-modal.tsx:216]: I tried putting it in the debounce first and it worked terribly. Digits were dropped, backspace only worked occasionally, and it was in general broken.

Debounce still has an effect as it prevents saving the settings on every single change. It's only the display in the control that isn't debounced.
